[package]
name = "sam-user_get_exercises"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.14.4"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["default"] }
lambda_http = "0.17.0"
models = {path = "../models"}