[package]
name = "sam-user_get_exercises"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "1.0.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["default", "rt", "rt-multi-thread", "macros"] }
lambda_http = "1.0.0"
models = {path = "../models"}