[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
#aws-sdk-dynamodb = "1.98.0"
#aws-config = "1.8.10"
sqlx = {version = "0.9.0-alpha.1", features = ["runtime-tokio", "postgres", "uuid", "chrono"]}
dotenv = "0.15.0"